# Generated by Selenium IDE
import pytest
from selenium.webdriver.common.by import By

from core.selenium.common import initialize_driver

class TestCreateNotepad():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}

  def teardown_method(self, method):
        self.driver.quit()

  def test_login(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(657, 715)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
  
  def test_editNotepad(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(657, 715)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.get("http://localhost:5000/notepad")
    self.driver.set_window_size(605, 625)
    self.driver.find_element(By.LINK_TEXT, "Edit").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(2)").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("test notepad! Im editing")
    self.driver.find_element(By.ID, "body").click()
    self.driver.find_element(By.ID, "body").send_keys("hello!!! Im edited")
    self.driver.find_element(By.ID, "submit").click()
    
  def test_deleteNotepad(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(657, 715)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.get("http://localhost:5000/notepad")
    self.driver.set_window_size(1280, 625)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
  def test_createNotepad(self):
    self.driver.get("http://localhost:5000/login")
    self.driver.set_window_size(657, 715)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "submit").click()
    self.driver.get("http://localhost:5000/notepad/create")
    self.driver.set_window_size(1374, 868)
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content").click()
    self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(3)").click()
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("test notepad!")
    self.driver.find_element(By.ID, "body").click()
    self.driver.find_element(By.ID, "body").send_keys("hello!!!")
    self.driver.find_element(By.ID, "submit").click()
  